wandb_version: 1

batchsize:
  desc: null
  value: 8
train_epoch:
  desc: null
  value: 500
height:
  desc: null
  value: 256
width:
  desc: null
  value: 256
workers:
  desc: null
  value: 4
lr_ft:
  desc: null
  value: 0.01
lr_new:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0005
device:
  desc: null
  value: '0'
redirector:
  desc: null
  value: true
use_bn:
  desc: null
  value: true
use_pretrain:
  desc: null
  value: false
pretrain_model:
  desc: null
  value: path_to_model.pt
checkpoint:
  desc: null
  value: ./exp
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712500112.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.6
      6: 4.32.1
      8:
      - 3
      - 5
      13: windows-amd64
